Check for inno setup in configure

diff --git a/Windows/configure b/Windows/configure
--- a/Windows/configure
+++ b/Windows/configure
@@ -89,6 +89,22 @@ else
     echo "found"
 fi
 
+# Check for inno setup compiler
+printf "Checking for Inno Setup Compiler..."
+if command -v "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" &> /dev/null
+then
+    $ISCC="C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
+    echo $ISCC
+elif command -v "iscc" &> /dev/null
+then
+    ISCC="iscc"
+    echo $ISCC
+else
+    echo "not found"
+    echo "Inno Setup Compiler not found. Please install it to continue."
+    exit 1
+fi
+
 # Install required python packages
 echo "Installing required packages"
 if python3 -m pip install -r $requirements --break-system-packages &> /dev/null; then
