Check for gettext in configure

diff --git a/macOS/patches/configure b/macOS/patches/configure
--- a/macOS/patches/configure
+++ b/macOS/patches/configure
@@ -61,6 +61,27 @@ else
     echo "available"
 fi
 
+# Check for gettext
+printf "Checking for gettext..."
+if printf '%s\n' "$@" | grep -q -- "^--gettext="; then
+    gettext_arg=$(printf '%s\n' "$@" | grep -m1 '^--gettext=')
+    gettext_path="${gettext_arg#--gettext=}"
+    echo "$gettext_path"
+elif [ -f /opt/gettext/bin/gettext ]; then
+    gettext_path="/opt/gettext/bin/gettext"
+    echo "$gettext_path"
+elif [ -f /usr/local/bin/gettext ]; then
+    gettext_path="/usr/local/bin/gettext"
+    echo "$gettext_path"
+elif [ -d $(brew --prefix gettext) ]; then
+    gettext_path="$(brew --prefix gettext)/bin/gettext"
+    echo "$gettext_path"
+else
+    echo "not found"
+    echo "gettext not found. Install it to continue."
+    exit 1
+fi
+
 # Check for idlelib
 printf "Checking if python3 supports idlelib..."
 if ! command -v python3 -c 'import idlelib' &> /dev/null
