Do same for macOS configure script

diff --git a/macOS/patches/configure b/macOS/patches/configure
--- a/macOS/patches/configure
+++ b/macOS/patches/configure
@@ -1,30 +1,35 @@
 #!/bin/bash
 
 # Check for Python 3
+printf "Checking for python3..."
 if ! command -v python3 &> /dev/null
 then
+    echo "not found"
     echo "Python 3 not found. Please install it to continue."
     exit 1
 else
-    echo "Python 3 is installed."
+    echo "found"
 fi
 
 # Check for pip3
+printf "Checking for pip3..."
 if ! command -v pip3 &> /dev/null
 then
-    echo "pip3 not found. Installing with python..."
-    wget https://bootstrap.pypa.io/get-pip.py
-    python3 get-pip.py
-    python3 -m pip install --upgrade pip
+    echo "not found"
+    echo "pip3 not found. Install it to continue."
+    exit 1
 else
-    echo "pip3 is installed."
+    echo "found"
 fi
 
+# Check for tkinter as it is required
+printf "Checking if python3 supports tkinter..."
 if ! command -v python3 -c 'import tkinter' &> /dev/null
 then
+    echo "not available"
     echo "Tkinter not available. It is a core framework and required for compilation. Please compile python with tkinter or install a package containing tkinter to continue."
 else
-    echo "Tkinter is available."
+    echo "available"
 fi
 
 if ! command -v tar &> /dev/null
