Rewrite configure script to work like a conventional configure script

diff --git a/Linux/configure b/Linux/configure
--- a/Linux/configure
+++ b/Linux/configure
@@ -1,27 +1,76 @@
 #!/bin/bash
 
 # Check for Python 3
+printf "Checking for python3..."
 if ! command -v python3 &> /dev/null
 then
+    echo "not found"
     echo "Python 3 not found. Please install it to continue."
     exit 1
 else
-    echo "Python 3 is installed."
+    echo "found"
 fi
 
 # Check for pip3
+printf "Checking for pip3..."
 if ! command -v pip3 &> /dev/null
 then
+    echo "not found"
     echo "pip3 was not found. Please install it to your respective Python 3 installation to continue."
+    exit 1
 else
-    echo "pip3 is installed."
+    echo "found"
 fi
 
+# Check if tkinter is available
+printf "Checking if python3 supports tkinter..."
 if ! command -v python3 -c 'import tkinter' &> /dev/null
 then
+    echo "not available"
     echo "Tkinter not available. It is a core framework and required for compilation. Please compile python with tkinter or install a package containing tkinter to continue."
+    exit 1
 else
-    echo "Tkinter is available."
+    echo "available"
+fi
+
+# Check for some dpkg and apt packages
+
+printf "Checking if patchelf is installed..."
+if ! command -v patchelf >/dev/null 2>&1; then
+    echo "not installed"
+    echo "patchelf is not installed. Please install it to continue."
+    exit 1
+else
+    echo "installed"
+fi
+
+printf "Checking if python3-tk is installed..."
+if ! dpkg -l | grep python3-tk >/dev/null 2>&1; then
+    echo "not installed"
+    echo "python3-tk is not installed. Please install it to continue."
+    exit 1
+else
+    echo "installed"
+fi
+
+printf "Checking if python3-dev is installed..."
+if ! dpkg -l | grep python3-dev >/dev/null 2>&1; then
+    echo "not installed"
+    echo "python3-dev is not installed. Please install it to continue."
+    exit 1
+else
+    echo "installed"
+fi
+
+# Check for tar
+printf "Checking for tar..."
+if ! command -v tar &> /dev/null
+then
+    echo "not found"
+    echo "Tar not found. Install it before continuing."
+    exit 1
+else
+    echo "found"
 fi
 
 # Install required python packages
@@ -33,35 +82,5 @@ else
     python3 -m pip install -r requirements.txt
 fi
 echo "done"
-
-# Install tk
-if ! command -v patchelf >/dev/null 2>&1; then
-    echo "patchelf is not installed. Please install it to continue."
-    exit 1
-else
-    echo "patchelf is installed."
-fi
-
-if ! dpkg -l | grep python3-tk >/dev/null 2>&1; then
-    echo "python3-tk is not installed. Please install it to continue."
-    exit 1
-else
-    echo "python3-tk is installed."
-fi
-
-if ! dpkg -l | grep python3-dev >/dev/null 2>&1; then
-    echo "python3-dev is not installed. Please install it to continue."
-    exit 1
-else
-    echo "python3-dev is installed."
-fi
-
-if ! command -v tar &> /dev/null
-then
-    echo "Tar not found. Install it before continuing."
-    exit 1
-else
-    echo "Tar is installed."
-fi
 
 echo "Now run 'make' to build."
