Add compatibility to configure script for the python that comes from apt on debian-based distros

diff --git a/Linux/configure b/Linux/configure
--- a/Linux/configure
+++ b/Linux/configure
@@ -19,7 +19,9 @@ fi
 
 # Install required python packages
 echo "Installing required packages"
-python3 -m pip install -r requirements.txt --break-system-packages
+if ! command -v python3 -m pip install -r requirements.txt --break-system-packages >/dev/null 2>&1; then
+    echo "Command failed, probably because this is running on python that comes from apt on Debian-based distros, running without --break-system-packages"
+    python3 -m pip install -r requirements.txt
 echo "done"
 
 # Install tk
