Add tar to the requirements

diff --git a/Linux/configure b/Linux/configure
--- a/Linux/configure
+++ b/Linux/configure
@@ -49,4 +49,12 @@ else
     echo "python3-dev is installed."
 fi
 
+if ! command -v tar &> /dev/null
+then
+    echo "Tar not found. Install it before continuing."
+    exit 1
+else
+    echo "Tar is installed."
+fi
+
 echo "Now run 'make' to build."
diff --git a/macOS/patches/configure b/macOS/patches/configure
--- a/macOS/patches/configure
+++ b/macOS/patches/configure
@@ -20,6 +20,14 @@ else
     echo "pip3 is installed."
 fi
 
+if ! command -v tar &> /dev/null
+then
+    echo "Tar not found. Install it before continuing."
+    exit 1
+else
+    echo "Tar is installed."
+fi
+
 # Install required python packages
 echo "Installing required packages"
 pip3 install -r requirements.txt --break-system-packages
