Make sure to check whether python distribution comes with tkinter before compiling on it

diff --git a/Linux/configure b/Linux/configure
--- a/Linux/configure
+++ b/Linux/configure
@@ -17,6 +17,13 @@ else
     echo "pip3 is installed."
 fi
 
+if ! command -v python3 -c 'import tkinter' &> /dev/null
+then
+    echo "Tkinter not available. It is a core framework and required for compilation. Please compile python with tkinter or install a package containing tkinter to continue."
+else
+    echo "Tkinter is available."
+fi
+
 # Install required python packages
 echo "Installing required packages"
 if python3 -m pip install -r requirements.txt --break-system-packages &> /dev/null; then
