Update dpinstall

diff --git a/Linux/dpinstall b/Linux/dpinstall
--- a/Linux/dpinstall
+++ b/Linux/dpinstall
@@ -7,7 +7,13 @@ echo "Updating apt first..."
 yes | sudo apt-get update
 
 echo "Installing packages..."
-yes | sudo apt-get install python3.12 python3.12-tk python3.12-pip python3.12-dev patchelf tar
+if ! command -v yes | sudo apt-get install python3.12 python3.12-tk python3.12-pip python3.12-dev patchelf tar &> /dev/null
+then
+    echo "done"
+else
+    echo "Command failed, probably because Deadsnakes PPA is not installed. Please add the deadsnakes PPA to continue.
+    exit 1
+fi
 
 echo "done"
 
