Probably should not use the checker; apt is very wonky in exit codes

diff --git a/Linux/dpinstall b/Linux/dpinstall
--- a/Linux/dpinstall
+++ b/Linux/dpinstall
@@ -7,13 +7,19 @@ echo "Updating apt first..."
 yes | sudo apt-get update
 
 echo "Installing packages..."
-if ! command -v yes | sudo apt-get install python3.12 python3.12-tk python3.12-pip python3.12-dev patchelf tar
-then
-    echo "done"
-else
-    echo "Command failed, probably because Deadsnakes PPA is not installed. Please add the deadsnakes PPA to continue."
-    exit 1
-fi
+yes | sudo apt-get install python3.12 python3.12-tk python3.12-dev patchelf tar
+# if ! command -v yes | sudo apt-get install python3.12 python3.12-tk python3.12-dev patchelf tar
+# then
+#     echo "done"
+# else
+#     echo "Command failed, probably because Deadsnakes PPA is not installed. Please add the deadsnakes PPA to continue."
+#     exit 1
+# fi
+
+echo "Configuring pip..."
+sudo ln -sf $(which python3.12) /usr/bin/python3
+sudo ln -sf $(which python3.12) /usr/bin/python
+sudo python3 -m ensurepip --upgrade
 
 echo "Installing python packages with pip..."
 if python3 -m pip install -r requirements.txt --break-system-packages
